services:
  khoomi-server:
    depends_on:
      - redis
    build:
      context: .
    container_name: khoomi-api
    hostname: khoomi-api
    networks:
      - khoomi-net
    ports:
      - 8080:8080
    deploy:
      restart_policy:
        condition: on-failure
  redis:
    image: redis:latest
    container_name: khoomi-redis
    networks:
      - khoomi-net
    ports:
      - 6379:6379

networks:
  khoomi-net:
    driver: bridge
