FROM golang:latest AS build-stage
WORKDIR /app
COPY go.mod go.sum /app
RUN go mod download
COPY . /app
COPY .env /app

ENV GIN_MODE=release
ENV GOOS=linux
RUN go build -ldflags="-s -w" -buildvcs=false ./cmd/khoomi

FROM build-stage AS test-build-stage
RUN go test -v ./...

FROM gcr.io/distroless/base-debian11 AS build-release-stage
WORKDIR /
COPY --from=build-stage /khoomi /khoomi
COPY .env .env

EXPOSE 8080
USER nonroot:nonroot
ENTRYPOINT ["/khoomi"]
