# fly.toml app configuration file generated for khoomi on 2024-12-28T19:32:47+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'khoomi'
primary_region = 'lhr'

[build]

[env]
  PORT = '8080'

[[mounts]]
  source = 'khoomi_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
