# fly.toml app configuration file generated for khoomi on 2023-06-25T08:07:24+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "khoomi"
primary_region = "jnb"

[[mounts]]
  source = "khoomi_data"
  destination = "/data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
