# fly.toml app configuration file generated for bold-sky-1898 on 2023-05-21T15:10:14+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bold-sky-1898"
primary_region = "cdg"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
